### ISSUE TITLE
Piracy

### ISSUE THREAD

**Issue by Irvel** [janishar/mit-deep-learning-book-pdf#3]
People can read the book in http://deeplearningbook.org/
PDF is not provided due to piracy concerns.

Don't you care at all about the author?

**Comment by janishar** [comment]
@Irvel 
Please define the piracy in this context?

The http://deeplearningbook.org/ itself mention this:

> What is the best way to print the HTML format?
Printing seems to work best printing directly from the browser, using Chrome. Other browsers do not work as well.

This website is allowing to print the book directly from the browser.
I don't understand the logic behind presenting a book so everyone can read and print and say it's for piracy concerns. It illogical.
Beside the Author is  getting the popularity and his purpose fulfilled by spreading the knowledge. The content of the book is a master work and I have encouraged to buy this book in the readme and always keep a copy with self because it's that worth.
Thanks

**Comment by Irvel** [comment]
Well the author could provide the PDF himself but he doesn't. The PDF is more practical to read on, which is why he provides the book in HTML as a "soft-drm" technique.    
  
You are breaking the DRM by providing the PDF, thus piracy.

**Comment by janishar** [comment]
@Irvel 
```
What is the best way to print the HTML format?
Printing seems to work best printing directly from the browser, using Chrome. Other browsers do not work as well.
```
When you print from the browser then it's eventually converted into PDF. 

` The PDF is more practical to read on`
The HTML and its PDF rendering is visually the same and today's constant internet connection makes offline and online reading practically the same.

I don't think it's any violation given the information that the website provides. We can have difference of opinion but it's foolish from the Author's part to present the book and the instructions the way it's given if he intended to prevent the distribution without the money in exchange. Let the Author of the book correct this anomaly. If he does remove the HTML copy then I will remove this PDF too. 
Thanks.

**Comment by jbuddha** [comment]
This is Piracy. He specifically states that he should not redistribute it as pdf. You can print it for yourself, you are not supposed to redistribute it. The reason for keeping it online is so that people will get more interested buy a physical copy. 

**Can I get a PDF of this book?**
No, our contract with MIT Press forbids distribution of too easily copied electronic formats of the book.

**Why are you using HTML format for the web version of the book?**
This format is a sort of weak DRM required by our contract with MIT Press. It's intended to discourage unauthorized copying/editing of the book.

**Comment by janishar** [comment]
@jbuddha 
1. ** No, our contract with MIT Press forbids distribution of too easily copied electronic formats of the book.** : It says that the contract between author and MIT press is that the author would not distribute by themselves the PDF version. It doesn't mention any clause that anyone else apart from them can not put it in the public domain.
2. **It's intended to discourage unauthorized copying/editing of the book.** : It is to discourage and not to prohibit.

The book itself nowhere in the text mention the distribution copyright. If you can show any such clause in the book then I will remove it happily from here. 

If the publication or the author show any objection here then also I will remove it.

It's not piracy. It is in the public domain.
